name: Lint

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v2

      - name: Vue 2
        continue-on-error: true
        run: |
          cd Vue2
          yarn install
          yarn eslint src --ext .vue,.ts
          cd ..

      - name: Vue 3
        continue-on-error: true
        run: |
          cd Vue3
          yarn install
          yarn eslint src --ext .vue,.ts
          cd ..
